# Generated by Django 4.2.5 on 2023-09-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("logo_image", models.CharField(blank=True, max_length=100, null=True)),
                ("about_us", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("employee_size", models.IntegerField(blank=True, null=True)),
                (
                    "website_link",
                    models.URLField(blank=True, max_length=250, null=True),
                ),
                (
                    "founder_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("founded_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Business Information",
                "db_table": "business_informations",
            },
        ),
    ]
