version: "3"
services:
  app:
    build: .
    command: gunicorn   --workers=2 --timeout 120 --log-level debug --access-logfile  /usr/src/app/logs/gunicorn/access.log --error-logfile /usr/src/app/logs/gunicorn/error.log --worker-connections 3000 --bind=0.0.0.0:8000 assessment.wsgi:application 
    container_name: app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_HOST_AUTH_METHOD=trust

  
      
  nginx:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  postgres_data: